name: Docker GPU Test (self-hosted)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted, "Linux"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: scripts/cli.dockerfile
            image: shipai/boa-cli
          #   - dockerfile: scripts/rabbitmq.dockerfile
          #     image: shipai/boa-rabbitmq
          #   - dockerfile: scripts/task_gpu.dockerfile
          #     image: shipai/boa-worker-gpu
          #   - dockerfile: scripts/task.dockerfile
          #     image: shipai/boa-worker-cpu
          #   - dockerfile: scripts/orthanc.dockerfile
          #     image: shipai/boa-orthanc
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Build image
        run: |
          docker build -t "${{ matrix.image }}:test" -f "${{ matrix.dockerfile }}" .
      - name: Download DICOM
        run: |
          zip_file=./test_images/dicoms.zip
          dicom_dir=./test_images/dicoms

          mkdir -p "$dicom_dir"
          curl --fail --show-error --silent --location \
            --max-time 120 \
            --get "https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage" \
            --data-urlencode "SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.1427.5885.222751041402610322644964911342" \
            --data-urlencode "NewFileNames=Yes" \
            --output "$zip_file"
          unzip -q "$zip_file" -d "$dicom_dir"
          rm "$zip_file"
      - name: Run GPU inference
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE/test_images/dicoms:/dicoms" \
            -v "$GITHUB_WORKSPACE/test_images/boa_cli/gpu_cnr:/workspace" \
            -v ~/.totalsegmentator:/app/weights \
            --runtime=nvidia \
            -e NVIDIA_VISIBLE_DEVICES=5 \
            --user $(id -u):$(id -g) \
            --shm-size=8g --ulimit memlock=-1 --ulimit stack=67108864 \
            --entrypoint /bin/sh \
            "${{ matrix.image }}:test" \
            -c \
            "python body_organ_analysis --input-image /dicoms --output-dir /workspace/ --models bca+heartchambers_highres --verbose"
